============================= test session starts =============================
platform win32 -- Python 3.12.10, pytest-8.4.1, pluggy-1.6.0 -- C:\Users\SahilSubba\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe
cachedir: .pytest_cache
metadata: {'Python': '3.12.10', 'Platform': 'Windows-11-10.0.26100-SP0', 'Packages': {'pytest': '8.4.1', 'pluggy': '1.6.0'}, 'Plugins': {'allure-pytest': '2.14.3', 'anyio': '4.9.0', 'html': '4.1.1', 'metadata': '3.1.1', 'rerunfailures': '15.1', 'xdist': '3.7.0'}, 'JAVA_HOME': 'C:\\Program Files\\Java\\jdk-17'}
rootdir: C:\Users\SahilSubba\Desktop\javascript\RsatA_project\build-1.2
configfile: pytest.ini
testpaths: tests
plugins: allure-pytest-2.14.3, anyio-4.9.0, html-4.1.1, metadata-3.1.1, rerunfailures-15.1, xdist-3.7.0
collecting ... collected 1 item / 2 errors

=================================== ERRORS ====================================
______________ ERROR collecting tests/script_data_test_1_test.py ______________
ImportError while importing test module 'C:\Users\SahilSubba\Desktop\javascript\RsatA_project\build-1.2\tests\script_data_test_1_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tests\script_data_test_1_test.py:10: in <module>
    from Utils.getExcelData import read_test_data
E   ImportError: cannot import name 'read_test_data' from 'Utils.getExcelData' (C:\Users\SahilSubba\Desktop\javascript\RsatA_project\build-1.2\Utils\getExcelData.py)
______________ ERROR collecting tests/script_data_test_3_test.py ______________
ImportError while importing test module 'C:\Users\SahilSubba\Desktop\javascript\RsatA_project\build-1.2\tests\script_data_test_3_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tests\script_data_test_3_test.py:10: in <module>
    from Utils.getExcelData import read_test_data
E   ImportError: cannot import name 'read_test_data' from 'Utils.getExcelData' (C:\Users\SahilSubba\Desktop\javascript\RsatA_project\build-1.2\Utils\getExcelData.py)
- generated xml file: C:\Users\SahilSubba\Desktop\javascript\RsatA_project\build-1.2\reports\report.xml -
- Generated html report: file:///C:/Users/SahilSubba/Desktop/javascript/RsatA_project/build-1.2/reports/report.html -
=========================== short test summary info ===========================
ERROR tests/script_data_test_1_test.py
ERROR tests/script_data_test_3_test.py
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!
============================== 2 errors in 1.01s ==============================
